apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contoso-dev

bases:
  - ../../../../base/02-rbac/openshift-gitops
  - ../../../../base/02-rbac/contoso-cicd-pipelines

resources:
  - namespace.yaml